# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0008_courseuserrelation_positive_completion_possible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('course', models.ManyToManyField(to='Course.Course')),
            ],
        ),
    ]
