# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 21:47
from __future__ import unicode_literals

import FileUpload.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuroraUser', '0001_initial'),
        ('Elaboration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaboration_version', models.TextField(default='original')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('upload_file', models.FileField(upload_to=FileUpload.models.get_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=FileUpload.models.get_thumbnail_path)),
                ('elaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elaboration.Elaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuroraUser.AuroraUser')),
            ],
        ),
    ]
