# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 20:20
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraUser', '0003_aurorauser_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aurorauser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
