# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0016_courseuserrelation_review_group'),
        ('AuroraUser', '0004_auto_20170428_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='aurorauser',
            name='courses',
            field=models.ManyToManyField(through='Course.CourseUserRelation', to='Course.Course'),
        ),
    ]
