# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuroraUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('short_title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('course_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('review_karma', models.DecimalField(decimal_places=19, default=0.0, max_digits=20)),
                ('review_group', models.PositiveSmallIntegerField(default=1)),
                ('top_reviewer', models.BooleanField(default=False)),
                ('positive_completion_possible', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuroraUser.AuroraUser')),
            ],
        ),
    ]
