# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_auto_20171012_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tuwel_course_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
