# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_auto_20171012_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tuwel_course_stream_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
