# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_auto_20171016_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='course',
            name='tuwel_course_stream_id',
            field=models.PositiveIntegerField(),
        ),
    ]
