# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_auto_20171016_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseuserrelation',
            name='review_group',
        ),
        migrations.RemoveField(
            model_name='courseuserrelation',
            name='review_karma',
        ),
        migrations.AddField(
            model_name='courseuserrelation',
            name='review_karma_students',
            field=models.DecimalField(decimal_places=19, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='courseuserrelation',
            name='review_karma_tutors',
            field=models.DecimalField(decimal_places=19, default=0.0, max_digits=20),
        ),
    ]
