# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraUser', '0005_aurorauser_courses'),
        ('Course', '0016_courseuserrelation_review_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(through='Course.CourseUserRelation', to='AuroraUser.AuroraUser'),
        ),
    ]
