# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='username',
            field=models.TextField(default='humpty'),
            preserve_default=False,
        ),
    ]
