---
# This is run as user `root`
# Creates DB, users and databases

- name: initialize PostgreSQL
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
           creates=/var/lib/pgsql/9.6/data/postgresql.conf

- name: Start PostgreSQL and enable at boot
  systemd: name=postgresql-9.6
           enabled=yes
           state=started

- postgresql_user: name={{ dbuser }}
                   password={{ dbpassword }}
  become: yes
  become_user: postgres

- name: create database {{ dbname }}
  postgresql_db: name={{ dbname }}
                 owner={{ dbuser }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
  become: yes
  become_user: postgres

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres

