---
- name: add yarn repo
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo

- name: install yarn
  yum: name=yarn

- name: install create-react-app
  command: yarn global add create-react-app
           creates=/usr/local/bin/create-react-app