# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Review', '0005_auto_20170227_1416'),
        ('ReviewQuestion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review.Review')),
                ('review_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewQuestion.ReviewQuestion')),
            ],
        ),
    ]
