# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReviewQuestion', '0001_initial'),
        ('ReviewAnswer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanswer',
            name='review_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewQuestion.ReviewQuestion'),
        ),
    ]
