# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:03
from __future__ import unicode_literals

from django.db import migrations

def kill_duplicate_review_evaluations(apps, schema_editor):
    ReviewEvaluation = apps.get_model("Review", "ReviewEvaluation")
    all_combinations = ReviewEvaluation.objects.values_list("user_id",
                                                            "review_id")
    for (user_id, review_id) in all_combinations:
        all_entries = ReviewEvaluation.objects.filter(user_id = user_id,
                                                review_id = review_id
                                                ).order_by("creation_time")
        first_entry = all_entries.first()
        all_entries.exclude(id = first_entry.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0005_auto_20170227_1416'),
    ]

    operations = [
        migrations.RunPython(kill_duplicate_review_evaluations,
                             lambda a, s: None),
    ]
