# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraUser', '0005_aurorauser_courses'),
        ('Review', '0006_auto_20171116_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewevaluation',
            unique_together=set([('user', 'review')]),
        ),
    ]
