# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('text', models.TextField(null=True)),
                ('boolean_answer', models.BooleanField(default=False)),
                ('visible_to_author', models.BooleanField(default=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenge.Challenge')),
            ],
        ),
    ]
