# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('Challenge', '0001_initial'),
        ('AuroraUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('elaboration_text', models.TextField(default='')),
                ('revised_elaboration_text', models.TextField(default='')),
                ('revised_elaboration_changelog', models.TextField(default='')),
                ('most_helpful_other_user', models.IntegerField(null=True)),
                ('submission_time', models.DateTimeField(null=True)),
                ('extra_review_question', models.TextField(default='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenge.Challenge')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuroraUser.AuroraUser')),
            ],
        ),
    ]
