# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 21:47
from __future__ import unicode_literals

import Challenge.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Challenge.models.challenge_image_path)),
                ('accepted_files', models.CharField(blank=True, default='image/*,application/pdf', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Challenge.Challenge')),
            ],
        ),
    ]
